from __future__ import annotations

import argparse

from ait.adapters import ADAPTERS
from ait.cli_installation import package_version


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ait")
    parser.add_argument("--version", action="version", version=f"%(prog)s {package_version()}")
    parser.add_argument("--no-hints", action="store_true")
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("init")
    init_parser.add_argument(
        "--adapter",
        choices=tuple(name for name in sorted(ADAPTERS) if name != "shell"),
        action="append",
        dest="init_adapters",
    )
    init_parser.add_argument("--format", choices=("text", "json"), default="text")
    init_parser.add_argument("--shell", action="store_true")
    init_parser.add_argument(
        "--no-shell-install",
        action="store_true",
        help="skip auto-installing the per-cd shell hook into ~/.zshrc / ~/.bashrc",
    )
    intent_parser = subparsers.add_parser("intent")
    intent_subparsers = intent_parser.add_subparsers(dest="intent_command")
    intent_new = intent_subparsers.add_parser("new")
    intent_new.add_argument("title")
    intent_new.add_argument("--description")
    intent_new.add_argument("--kind")
    intent_show = intent_subparsers.add_parser("show")
    intent_show.add_argument("intent_id")
    intent_abandon = intent_subparsers.add_parser("abandon")
    intent_abandon.add_argument("intent_id")
    intent_supersede = intent_subparsers.add_parser("supersede")
    intent_supersede.add_argument("intent_id")
    intent_supersede.add_argument("--by", required=True)
    intent_list = intent_subparsers.add_parser("list")
    intent_list.add_argument("--status")
    intent_list.add_argument("--kind")
    intent_list.add_argument("--tag")
    intent_list.add_argument("--limit", type=int, default=100)
    intent_list.add_argument("--offset", type=int, default=0)
    intent_list.add_argument("--format", choices=("table", "jsonl"), default="table")

    attempt_parser = subparsers.add_parser("attempt")
    attempt_subparsers = attempt_parser.add_subparsers(dest="attempt_command")
    attempt_new = attempt_subparsers.add_parser("new")
    attempt_new.add_argument("intent_id")
    attempt_new.add_argument("--agent-id")
    attempt_show = attempt_subparsers.add_parser("show")
    attempt_show.add_argument("attempt_id")
    attempt_commit = attempt_subparsers.add_parser("commit")
    attempt_commit.add_argument("attempt_id")
    attempt_commit.add_argument("-m", "--message", required=True)
    attempt_promote = attempt_subparsers.add_parser("promote")
    attempt_promote.add_argument("attempt_id")
    attempt_promote.add_argument("--to", required=True)
    attempt_rebase = attempt_subparsers.add_parser("rebase")
    attempt_rebase.add_argument("attempt_id")
    attempt_rebase.add_argument("--onto", required=True)
    attempt_discard = attempt_subparsers.add_parser("discard")
    attempt_discard.add_argument("attempt_id")
    attempt_verify = attempt_subparsers.add_parser("verify")
    attempt_verify.add_argument("attempt_id")
    attempt_list = attempt_subparsers.add_parser("list")
    attempt_list.add_argument("--intent")
    attempt_list.add_argument("--reported-status")
    attempt_list.add_argument("--verified-status")
    attempt_list.add_argument("--agent")
    attempt_list.add_argument("--limit", type=int, default=100)
    attempt_list.add_argument("--offset", type=int, default=0)
    attempt_list.add_argument("--format", choices=("table", "jsonl"), default="table")

    query_parser = subparsers.add_parser("query")
    query_parser.add_argument("--on", choices=("intent", "attempt"), default="attempt")
    query_parser.add_argument("expression", nargs="?")
    query_parser.add_argument("--limit", type=int, default=100)
    query_parser.add_argument("--offset", type=int, default=0)
    query_parser.add_argument("--format", choices=("table", "jsonl"), default="table")

    blame_parser = subparsers.add_parser("blame")
    blame_parser.add_argument("target")

    run_parser = subparsers.add_parser("run")
    run_parser.add_argument("--adapter", choices=tuple(sorted(ADAPTERS)), default="shell")
    run_parser.add_argument("--agent")
    run_parser.add_argument("--intent")
    run_parser.add_argument("--kind")
    run_parser.add_argument("--description")
    run_parser.add_argument("--commit-message")
    run_parser.add_argument("--no-auto-commit", action="store_true")
    run_parser.add_argument("--with-context", action="store_true")
    run_parser.add_argument("--format", choices=("json", "text"), default="json")
    run_parser.add_argument("--port", type=int, action="append", dest="dev_ports")
    run_parser.add_argument("--check-port", type=int, action="append", dest="dev_check_ports")
    run_parser.add_argument("run_command", nargs=argparse.REMAINDER)

    dev_parser = subparsers.add_parser("dev")
    dev_subparsers = dev_parser.add_subparsers(dest="dev_command")
    dev_status = dev_subparsers.add_parser("status")
    dev_status.add_argument("--port", type=int, action="append", dest="ports")
    dev_status.add_argument("--format", choices=("text", "json"), default="text")
    dev_preview = dev_subparsers.add_parser("preview")
    dev_preview.add_argument("url")
    dev_preview.add_argument("--file")
    dev_preview.add_argument("--format", choices=("text", "json"), default="text")
    dev_run = dev_subparsers.add_parser("run")
    dev_run.add_argument("--port", type=int, action="append", dest="ports")
    dev_run.add_argument("--format", choices=("text", "json"), default="text")
    dev_run.add_argument("dev_run_command", nargs=argparse.REMAINDER)
    dev_stop = dev_subparsers.add_parser("stop")
    dev_stop.add_argument("--port", type=int)
    dev_stop.add_argument("--force", action="store_true")
    dev_stop.add_argument("--format", choices=("text", "json"), default="text")

    context_parser = subparsers.add_parser("context")
    context_parser.add_argument("intent_id")
    context_parser.add_argument("--format", choices=("text", "json"), default="text")

    memory_parser = subparsers.add_parser("memory")
    memory_parser.add_argument("--limit", type=int, default=8)
    memory_parser.add_argument("--path", dest="path_filter")
    memory_parser.add_argument("--topic")
    memory_parser.add_argument("--promoted-only", action="store_true")
    memory_parser.add_argument("--budget-chars", type=int)
    memory_parser.add_argument("--format", choices=("text", "json"), default="text")
    memory_subparsers = memory_parser.add_subparsers(dest="memory_command")
    memory_facts = memory_subparsers.add_parser("facts")
    memory_facts.add_argument("--status")
    memory_facts.add_argument("--kind")
    memory_facts.add_argument("--topic")
    memory_facts.add_argument("--include-superseded", action="store_true")
    memory_facts.add_argument("--limit", type=int, default=100)
    memory_facts.add_argument("--format", choices=("text", "json"), default="text")
    memory_retrievals = memory_subparsers.add_parser("retrievals")
    memory_retrievals.add_argument("--attempt")
    memory_retrievals.add_argument("--limit", type=int, default=50)
    memory_retrievals.add_argument("--format", choices=("text", "json"), default="text")
    memory_eval = memory_subparsers.add_parser("eval")
    memory_eval.add_argument("--attempt")
    memory_eval.add_argument("--limit", type=int, default=50)
    memory_eval.add_argument("--format", choices=("text", "json"), default="text")
    memory_note = memory_subparsers.add_parser("note")
    memory_note_subparsers = memory_note.add_subparsers(dest="memory_note_command")
    memory_note_add = memory_note_subparsers.add_parser("add")
    memory_note_add.add_argument("body")
    memory_note_add.add_argument("--topic")
    memory_note_add.add_argument("--source", default="manual")
    memory_note_add.add_argument("--format", choices=("text", "json"), default="json")
    memory_note_list = memory_note_subparsers.add_parser("list")
    memory_note_list.add_argument("--topic")
    memory_note_list.add_argument("--limit", type=int, default=100)
    memory_note_list.add_argument("--format", choices=("text", "json"), default="text")
    memory_note_remove = memory_note_subparsers.add_parser("remove")
    memory_note_remove.add_argument("note_id")
    memory_note_remove.add_argument("--format", choices=("text", "json"), default="json")
    memory_search = memory_subparsers.add_parser("search")
    memory_search.add_argument("query")
    memory_search.add_argument("--limit", type=int, default=8)
    memory_search.add_argument("--ranker", choices=("vector", "lexical"), default="vector")
    memory_search.add_argument("--format", choices=("text", "json"), default="text")
    memory_recall = memory_subparsers.add_parser("recall")
    memory_recall.add_argument("query", nargs="?")
    memory_recall.add_argument("--auto", action="store_true")
    memory_recall.add_argument("--agent")
    memory_recall.add_argument("--kind")
    memory_recall.add_argument("--description")
    memory_recall.add_argument("--command-text")
    memory_recall.add_argument("--limit", type=int, default=6)
    memory_recall.add_argument("--budget-chars", type=int, default=4000)
    memory_recall.add_argument("--include-unhealthy", action="store_true")
    memory_recall.add_argument("--format", choices=("text", "json"), default="text")
    memory_lint = memory_subparsers.add_parser("lint")
    memory_lint.add_argument("--fix", action="store_true")
    memory_lint.add_argument("--max-chars", type=int, default=6000)
    memory_lint.add_argument("--format", choices=("text", "json"), default="text")
    memory_import = memory_subparsers.add_parser("import")
    memory_import.add_argument("--source", default="auto")
    memory_import.add_argument("--path", action="append", dest="import_paths")
    memory_import.add_argument("--topic", default="agent-memory")
    memory_import.add_argument("--max-chars", type=int, default=6000)
    memory_import.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph = memory_subparsers.add_parser("graph")
    memory_graph_subparsers = memory_graph.add_subparsers(dest="memory_graph_command")
    memory_graph_build = memory_graph_subparsers.add_parser("build")
    memory_graph_build.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph_show = memory_graph_subparsers.add_parser("show")
    memory_graph_show.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph_show.add_argument("--budget-chars", type=int)
    memory_graph_query = memory_graph_subparsers.add_parser("query")
    memory_graph_query.add_argument("query")
    memory_graph_query.add_argument("--limit", type=int, default=8)
    memory_graph_query.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph_brief = memory_graph_subparsers.add_parser("brief")
    memory_graph_brief.add_argument("query", nargs="?")
    memory_graph_brief.add_argument("--auto", action="store_true")
    memory_graph_brief.add_argument("--explain", action="store_true")
    memory_graph_brief.add_argument("--agent")
    memory_graph_brief.add_argument("--kind")
    memory_graph_brief.add_argument("--description")
    memory_graph_brief.add_argument("--command-text")
    memory_graph_brief.add_argument("--limit", type=int, default=6)
    memory_graph_brief.add_argument("--budget-chars", type=int, default=5000)
    memory_graph_brief.add_argument("--format", choices=("text", "json"), default="text")
    memory_policy = memory_subparsers.add_parser("policy")
    memory_policy_subparsers = memory_policy.add_subparsers(dest="memory_policy_command")
    memory_policy_init = memory_policy_subparsers.add_parser("init")
    memory_policy_init.add_argument("--force", action="store_true")
    memory_policy_init.add_argument("--format", choices=("text", "json"), default="json")
    memory_policy_show = memory_policy_subparsers.add_parser("show")
    memory_policy_show.add_argument("--format", choices=("text", "json"), default="json")

    bootstrap_parser = subparsers.add_parser("bootstrap")
    bootstrap_parser.add_argument("name", choices=tuple(sorted(ADAPTERS)), nargs="?", default="claude-code")
    bootstrap_parser.add_argument("--format", choices=("text", "json"), default="json")
    bootstrap_parser.add_argument("--shell", action="store_true")
    bootstrap_parser.add_argument("--check", action="store_true")

    doctor_parser = subparsers.add_parser("doctor")
    doctor_parser.add_argument("name", choices=tuple(sorted(ADAPTERS)), nargs="?")
    doctor_parser.add_argument("--format", choices=("text", "json"), default="text")
    doctor_parser.add_argument("--fix", action="store_true")

    status_parser = subparsers.add_parser("status")
    status_parser.add_argument("name", choices=tuple(sorted(ADAPTERS)), nargs="?", default="claude-code")
    status_parser.add_argument("--format", choices=("text", "json"), default="text")
    status_parser.add_argument("--all", action="store_true", dest="all_adapters")

    upgrade_parser = subparsers.add_parser("upgrade")
    upgrade_parser.add_argument("--dry-run", action="store_true")
    upgrade_parser.add_argument("--format", choices=("text", "json"), default="text")

    graph_parser = subparsers.add_parser("graph")
    graph_parser.add_argument("--format", choices=("text", "json"), default="text")
    graph_parser.add_argument("--limit", type=int, default=20)
    graph_parser.add_argument("--html", action="store_true")
    graph_parser.add_argument("--output")
    graph_parser.add_argument("--agent")
    graph_parser.add_argument("--status")
    graph_parser.add_argument("--file", dest="file_path")

    repair_parser = subparsers.add_parser("repair")
    repair_parser.add_argument(
        "name",
        choices=tuple(name for name in sorted(ADAPTERS) if name != "shell"),
        nargs="?",
    )
    repair_parser.add_argument("--format", choices=("text", "json"), default="text")

    enable_parser = subparsers.add_parser("enable")
    enable_parser.add_argument(
        "--adapter",
        choices=tuple(name for name in sorted(ADAPTERS) if name != "shell"),
        action="append",
        dest="enable_adapters",
    )
    enable_parser.add_argument("--format", choices=("text", "json"), default="text")
    enable_parser.add_argument("--shell", action="store_true")

    shell_parser = subparsers.add_parser("shell")
    shell_subparsers = shell_parser.add_subparsers(dest="shell_command")
    shell_show = shell_subparsers.add_parser("show")
    shell_show.add_argument("--shell", choices=("zsh", "bash"), default="zsh")
    shell_install = shell_subparsers.add_parser("install")
    shell_install.add_argument("--shell", choices=("zsh", "bash"))
    shell_install.add_argument("--rc-path")
    shell_install.add_argument("--format", choices=("text", "json"), default="text")
    shell_uninstall = shell_subparsers.add_parser("uninstall")
    shell_uninstall.add_argument("--shell", choices=("zsh", "bash"))
    shell_uninstall.add_argument("--rc-path")
    shell_uninstall.add_argument("--format", choices=("text", "json"), default="text")

    adapter_parser = subparsers.add_parser("adapter")
    adapter_subparsers = adapter_parser.add_subparsers(dest="adapter_command")
    adapter_list = adapter_subparsers.add_parser("list")
    adapter_list.add_argument("--format", choices=("table", "json"), default="table")
    adapter_show = adapter_subparsers.add_parser("show")
    adapter_show.add_argument("name", choices=tuple(sorted(ADAPTERS)))
    adapter_show.add_argument("--format", choices=("text", "json"), default="text")
    adapter_doctor = adapter_subparsers.add_parser("doctor")
    adapter_doctor.add_argument("name", choices=tuple(sorted(ADAPTERS)))
    adapter_doctor.add_argument("--format", choices=("text", "json"), default="text")
    adapter_setup = adapter_subparsers.add_parser("setup")
    adapter_setup.add_argument("name", choices=tuple(sorted(ADAPTERS)))
    adapter_setup.add_argument("--target", default=".claude/settings.json")
    adapter_setup.add_argument("--print", action="store_true", dest="print_only")
    adapter_setup.add_argument("--install-wrapper", action="store_true")
    adapter_setup.add_argument("--install-direnv", action="store_true")

    subparsers.add_parser("reconcile")

    daemon_parser = subparsers.add_parser("daemon")
    daemon_subparsers = daemon_parser.add_subparsers(dest="daemon_command")
    daemon_subparsers.add_parser("start")
    daemon_subparsers.add_parser("stop")
    daemon_subparsers.add_parser("prune")
    daemon_subparsers.add_parser("status")
    daemon_subparsers.add_parser("serve")
    return parser
