from __future__ import annotations

import argparse

from ait.adapters import ADAPTERS
from ait.cli_installation import package_version
from ait.review_benchmark import DEFAULT_REAL_REVIEWER_BENCHMARK_TIMEOUT_SECONDS


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ait")
    parser.add_argument("--version", action="version", version=f"%(prog)s {package_version()}")
    parser.add_argument("--no-hints", action="store_true")
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("init")
    init_parser.add_argument(
        "--adapter",
        choices=tuple(name for name in sorted(ADAPTERS) if name != "shell"),
        action="append",
        dest="init_adapters",
    )
    init_parser.add_argument("--format", choices=("text", "json"), default="text")
    init_parser.add_argument("--shell", action="store_true")
    init_parser.add_argument(
        "--no-shell-install",
        action="store_true",
        help="skip auto-installing the per-cd shell hook into ~/.zshrc / ~/.bashrc",
    )
    intent_parser = subparsers.add_parser("intent")
    intent_subparsers = intent_parser.add_subparsers(dest="intent_command")
    intent_new = intent_subparsers.add_parser("new")
    intent_new.add_argument("title")
    intent_new.add_argument("--description")
    intent_new.add_argument("--kind")
    intent_show = intent_subparsers.add_parser("show")
    intent_show.add_argument("intent_id")
    intent_abandon = intent_subparsers.add_parser("abandon")
    intent_abandon.add_argument("intent_id")
    intent_supersede = intent_subparsers.add_parser("supersede")
    intent_supersede.add_argument("intent_id")
    intent_supersede.add_argument("--by", required=True)
    intent_list = intent_subparsers.add_parser("list")
    intent_list.add_argument("--status")
    intent_list.add_argument("--kind")
    intent_list.add_argument("--tag")
    intent_list.add_argument("--limit", type=int, default=100)
    intent_list.add_argument("--offset", type=int, default=0)
    intent_list.add_argument("--format", choices=("table", "jsonl"), default="table")

    attempt_parser = subparsers.add_parser(
        "attempt",
        help="advanced attempt inspection and low-level Git operations",
    )
    attempt_subparsers = attempt_parser.add_subparsers(dest="attempt_command")
    attempt_new = attempt_subparsers.add_parser("new")
    attempt_new.add_argument("intent_id")
    attempt_new.add_argument("--agent-id")
    attempt_show = attempt_subparsers.add_parser("show")
    attempt_show.add_argument("attempt_id")
    attempt_show.add_argument("--format", choices=("text", "json"))
    attempt_show.add_argument("--json", action="store_true", help="alias for --format json")
    attempt_commit = attempt_subparsers.add_parser("commit")
    attempt_commit.add_argument("attempt_id")
    attempt_commit.add_argument("-m", "--message", required=True)
    attempt_promote = attempt_subparsers.add_parser("promote")
    attempt_promote.add_argument("attempt_id")
    attempt_promote.add_argument("--to", required=True)
    attempt_land = attempt_subparsers.add_parser("land")
    attempt_land.add_argument("attempt_id")
    attempt_land.add_argument("--to")
    attempt_rebase = attempt_subparsers.add_parser("rebase")
    attempt_rebase.add_argument("attempt_id")
    attempt_rebase.add_argument("--onto", required=True)
    attempt_discard = attempt_subparsers.add_parser("discard")
    attempt_discard.add_argument("attempt_id")
    attempt_verify = attempt_subparsers.add_parser("verify")
    attempt_verify.add_argument("attempt_id")
    attempt_list = attempt_subparsers.add_parser("list")
    attempt_list.add_argument("--intent")
    attempt_list.add_argument("--reported-status")
    attempt_list.add_argument("--verified-status")
    attempt_list.add_argument("--agent")
    attempt_list.add_argument("--limit", type=int, default=100)
    attempt_list.add_argument("--offset", type=int, default=0)
    attempt_list.add_argument("--format", choices=("table", "jsonl"), default="table")
    attempt_alias = attempt_subparsers.add_parser("alias")
    attempt_alias_subparsers = attempt_alias.add_subparsers(dest="attempt_alias_command")
    attempt_alias_set = attempt_alias_subparsers.add_parser("set")
    attempt_alias_set.add_argument("attempt_id")
    attempt_alias_set.add_argument("alias")
    attempt_alias_set.add_argument("--force", action="store_true")
    attempt_alias_unset = attempt_alias_subparsers.add_parser("unset")
    attempt_alias_unset.add_argument("alias")
    attempt_alias_subparsers.add_parser("list")

    query_parser = subparsers.add_parser("query")
    query_parser.add_argument("--on", choices=("intent", "attempt"), default="attempt")
    query_parser.add_argument("expression", nargs="?")
    query_parser.add_argument("--limit", type=int, default=100)
    query_parser.add_argument("--offset", type=int, default=0)

    demo_parser = subparsers.add_parser(
        "demo",
        help="run a self-contained 60-second walkthrough of the ait flow (no API keys required)",
    )
    demo_parser.add_argument(
        "--clean",
        action="store_true",
        help="remove all prior /tmp/ait-demo-* directories and exit",
    )
    demo_parser.add_argument(
        "--keep",
        action="store_true",
        help="suppress the 'demo repo kept at ...' hint (use in CI)",
    )
    demo_parser.add_argument(
        "--quiet",
        action="store_true",
        help="suppress the explanatory output blocks",
    )
    demo_parser.add_argument(
        "--format",
        choices=("text", "json"),
        default="text",
        help="output format; json emits a single object for scripting",
    )
    query_parser.add_argument("--format", choices=("table", "jsonl"), default="table")

    blame_parser = subparsers.add_parser("blame")
    blame_parser.add_argument("target")

    session_parser = subparsers.add_parser("session", help="coordinate local multi-agent sessions")
    session_subparsers = session_parser.add_subparsers(dest="session_command")
    session_start = session_subparsers.add_parser("start")
    session_start.add_argument("title")
    session_start.add_argument("--agents", action="append")
    session_start.add_argument("--agent-command", action="append", help="explicit local command as agent=command")
    session_start.add_argument(
        "--claude-permission-mode",
        choices=("plan", "default", "acceptEdits", "auto", "dontAsk", "bypassPermissions"),
        help="consented Claude Code permission mode for real panel/council invocation",
    )
    session_start.add_argument(
        "--codex-sandbox",
        choices=("read-only", "workspace-write", "danger-full-access"),
        help="consented Codex sandbox mode for real panel/council invocation",
    )
    session_start.add_argument(
        "--codex-approval",
        choices=("untrusted", "on-request", "never"),
        help="consented Codex approval policy for real panel/council invocation",
    )
    session_start.add_argument("--format", choices=("text", "json"), default="text")
    session_ask = session_subparsers.add_parser("ask")
    session_ask.add_argument("selector")
    session_ask.add_argument("message")
    session_ask.add_argument("--format", choices=("text", "json"), default="text")
    session_show = session_subparsers.add_parser("show")
    session_show.add_argument("selector", nargs="?", default="latest")
    session_show.add_argument("--format", choices=("text", "json"), default="text")
    session_list = session_subparsers.add_parser("list")
    session_list.add_argument("--format", choices=("text", "json"), default="text")
    session_responses = session_subparsers.add_parser("responses")
    session_responses.add_argument("selector", nargs="?", default="latest")
    session_responses.add_argument("--format", choices=("text", "json", "jsonl"), default="text")
    session_export = session_subparsers.add_parser("export")
    session_export.add_argument("selector", nargs="?", default="latest")
    session_export.add_argument("--format", choices=("md", "json"), default="md")
    session_attach = session_subparsers.add_parser("attach")
    session_attach.add_argument("selector", nargs="?", default="latest")
    session_attach.add_argument("--layout", choices=("stacked", "prefix"), default="stacked")
    session_attach.add_argument("--agent")
    session_attach.add_argument("--read-only", action="store_true")
    session_attach.add_argument("--terminate-on-detach", action="store_true")
    session_attach.add_argument(
        "--input",
        action="append",
        dest="attach_input",
        help="script one routed input line for deterministic local testing",
    )
    session_attach.add_argument("--format", choices=("text", "json"), default="text")
    session_panes = session_subparsers.add_parser("panes")
    session_panes.add_argument("selector", nargs="?", default="latest")
    session_panes.add_argument("--format", choices=("text", "json"), default="text")
    session_send = session_subparsers.add_parser("send")
    session_send.add_argument("selector", nargs="?", default="latest")
    session_send.add_argument("message", nargs="?")
    session_send.add_argument("--to", dest="send_to")
    session_send.add_argument("--all", action="store_true", dest="send_all")
    session_send.add_argument("--format", choices=("text", "json"), default="text")
    session_kill = session_subparsers.add_parser("kill")
    session_kill.add_argument("selector", nargs="?", default="latest")
    session_kill.add_argument("--agent", required=True)
    session_kill.add_argument("--format", choices=("text", "json"), default="text")
    session_replay = session_subparsers.add_parser("replay")
    session_replay.add_argument("selector", nargs="?", default="latest")
    session_replay.add_argument("--turn", default="latest")
    session_replay.add_argument("--format", choices=("text", "json"), default="text")
    session_run = session_subparsers.add_parser("run")
    session_run.add_argument("selector", nargs="?", default="latest")
    session_run.add_argument("--mode", choices=("panel", "role", "council", "sequential"), default="panel")
    session_run.add_argument("--implementer", action="append")
    session_run.add_argument("--reviewer", action="append")
    session_run.add_argument("--allocation")
    session_run.add_argument("--package", action="append")
    session_run.add_argument("--timeout", type=int, default=60)
    session_run.add_argument("--format", choices=("text", "json"), default="text")
    session_panel = session_subparsers.add_parser("panel")
    session_panel.add_argument("selector", nargs="?", default="latest")
    session_panel.add_argument("--format", choices=("text", "json"), default="text")
    session_summarize = session_subparsers.add_parser("summarize")
    session_summarize.add_argument("selector", nargs="?", default="latest")
    session_summarize.add_argument("--format", choices=("text", "json"), default="text")
    session_decision = session_subparsers.add_parser("decision")
    session_decision.add_argument("selector", nargs="?", default="latest")
    session_decision.add_argument("--accept", required=True)
    session_decision.add_argument("--promote-memory", action="store_true")
    session_decision.add_argument("--format", choices=("text", "json"), default="text")
    session_attempt = session_subparsers.add_parser("attempt")
    session_attempt.add_argument("selector", nargs="?", default="latest")
    session_attempt.add_argument("--from", dest="from_response", required=True)
    session_attempt.add_argument("--agent")
    session_attempt.add_argument("--format", choices=("text", "json"), default="text")
    session_retry = session_subparsers.add_parser("retry")
    session_retry.add_argument("selector", nargs="?", default="latest")
    session_retry.add_argument("--response", required=True)
    session_retry.add_argument("--timeout", type=int, default=60)
    session_retry.add_argument("--format", choices=("text", "json"), default="text")
    session_cancel = session_subparsers.add_parser("cancel")
    session_cancel.add_argument("selector", nargs="?", default="latest")
    session_cancel.add_argument("--response")
    session_cancel.add_argument("--format", choices=("text", "json"), default="text")
    session_participant = session_subparsers.add_parser("participant")
    session_participant_subparsers = session_participant.add_subparsers(dest="participant_command")
    session_participant_list = session_participant_subparsers.add_parser("list")
    session_participant_list.add_argument("selector", nargs="?", default="latest")
    session_participant_list.add_argument("--format", choices=("text", "json"), default="text")
    session_participant_add = session_participant_subparsers.add_parser("add")
    session_participant_add.add_argument("selector", nargs="?", default="latest")
    session_participant_add.add_argument("--agent", required=True)
    session_participant_add.add_argument("--role", default="panelist")
    session_participant_add.add_argument("--command", dest="participant_command_template", help="explicit local command for this participant")
    session_participant_add.add_argument("--format", choices=("text", "json"), default="text")
    session_participant_remove = session_participant_subparsers.add_parser("remove")
    session_participant_remove.add_argument("selector", nargs="?", default="latest")
    session_participant_remove.add_argument("--participant", dest="participant_id")
    session_participant_remove.add_argument("--agent")
    session_participant_remove.add_argument("--reason")
    session_participant_remove.add_argument("--format", choices=("text", "json"), default="text")
    session_allocate = session_subparsers.add_parser("allocate")
    session_allocate.add_argument("selector", nargs="?", default="latest")
    session_allocate.add_argument("--strategy", choices=("adaptive",), default="adaptive")
    session_allocate.add_argument("--agents", action="append")
    session_allocate.add_argument("--package", action="append")
    session_allocate.add_argument("--dry-run", action="store_true")
    session_allocate.add_argument("--format", choices=("text", "json"), default="text")
    session_allocation = session_subparsers.add_parser("allocation")
    session_allocation_subparsers = session_allocation.add_subparsers(dest="allocation_command")
    session_allocation_accept = session_allocation_subparsers.add_parser("accept")
    session_allocation_accept.add_argument("selector", nargs="?", default="latest")
    session_allocation_accept.add_argument("--plan", required=True)
    session_allocation_accept.add_argument("--format", choices=("text", "json"), default="text")
    session_allocation_show = session_allocation_subparsers.add_parser("show")
    session_allocation_show.add_argument("selector", nargs="?", default="latest")
    session_allocation_show.add_argument("--plan", required=True)
    session_allocation_show.add_argument("--format", choices=("text", "json"), default="text")

    config_parser = subparsers.add_parser("config")
    config_subparsers = config_parser.add_subparsers(dest="config_command")
    config_show = config_subparsers.add_parser("show")
    config_show.add_argument("--format", choices=("text", "json"), default="text")

    policy_parser = subparsers.add_parser("policy", help="validate repo-local team policy")
    policy_subparsers = policy_parser.add_subparsers(dest="policy_command")
    policy_validate = policy_subparsers.add_parser("validate")
    policy_validate.add_argument("--format", choices=("text", "json"), default="text")
    policy_validate.add_argument("--json", action="store_true", help="alias for --format json")
    policy_show = policy_subparsers.add_parser("show")
    policy_show.add_argument("--format", choices=("text", "json"), default="text")
    policy_show.add_argument("--json", action="store_true", help="alias for --format json")

    metadata_parser = subparsers.add_parser("metadata", help="export or inspect local AIT metadata bundles")
    metadata_subparsers = metadata_parser.add_subparsers(dest="metadata_command")
    metadata_export = metadata_subparsers.add_parser("export")
    metadata_export.add_argument("--output")
    metadata_export.add_argument("--dry-run", action="store_true", default=True)
    metadata_export.add_argument("--format", choices=("text", "json"), default="text")
    metadata_export.add_argument("--json", action="store_true", help="alias for --format json")
    metadata_import = metadata_subparsers.add_parser("import")
    metadata_import.add_argument("--input", required=True)
    metadata_import.add_argument("--dry-run", action="store_true", required=True)
    metadata_import.add_argument("--format", choices=("text", "json"), default="text")
    metadata_import.add_argument("--json", action="store_true", help="alias for --format json")

    cleanup_parser = subparsers.add_parser("cleanup", help="inspect or remove safe internal AIT state")
    cleanup_parser.add_argument("--apply", action="store_true")
    cleanup_parser.add_argument("--force", action="store_true")
    cleanup_parser.add_argument("--format", choices=("text", "json"), default="text")
    cleanup_parser.add_argument("--older-than", type=int)
    cleanup_parser.add_argument("--include-orphans", action="store_true")
    cleanup_parser.add_argument("--artifacts", action="store_true")
    cleanup_parser.add_argument("--worktrees", action="store_true", default=True)

    apply_parser = subparsers.add_parser("apply", help="apply a successful AIT result")
    apply_parser.add_argument("attempt_id", nargs="?", default="latest")
    apply_parser.add_argument("--to", help="target branch for the result")
    apply_parser.add_argument(
        "--mode",
        choices=("auto", "current", "branch", "none"),
        default="auto",
        help="apply strategy: auto, current checkout, non-current branch, or hold",
    )
    apply_parser.add_argument("--format", choices=("text", "json"), default="text")
    apply_parser.add_argument("--json", action="store_true", help="alias for --format json")
    apply_parser.add_argument("--no-interactive", action="store_true")
    apply_parser.add_argument("--dry-run", action="store_true")
    apply_parser.add_argument("--debug", action="store_true", help="include internal workspace details")

    recover_parser = subparsers.add_parser("recover", help="show the latest held or failed AIT result")
    recover_parser.add_argument("attempt_id", nargs="?", default="latest")
    recover_parser.add_argument("--retry-apply", action="store_true", help="try applying the recoverable result again")
    recover_parser.add_argument("--create-integration", action="store_true", help="create an integration attempt for local-overlap recovery")
    recover_parser.add_argument("--auto-integrate", action="store_true", help="create an integration attempt and run enabled automatic integration steps")
    recover_parser.add_argument("--test", dest="integration_test_command", help="validation command to run inside the integration attempt")
    recover_parser.add_argument("--discard", action="store_true", help="discard a clean recoverable result")
    recover_parser.add_argument("--format", choices=("text", "json"), default="text")
    recover_parser.add_argument("--json", action="store_true", help="alias for --format json")
    recover_parser.add_argument("--no-interactive", action="store_true")
    recover_parser.add_argument("--dry-run", action="store_true")
    recover_parser.add_argument("--debug", action="store_true", help="include internal workspace details")

    resume_parser = subparsers.add_parser("resume", help="open a shell in a recoverable attempt workspace")
    resume_parser.add_argument("attempt_id", nargs="?", default="latest")
    resume_parser.add_argument("--print", action="store_true", help="print only the workspace path")
    resume_parser.add_argument("--finish", action="store_true", help="commit resumed workspace changes and try applying the attempt")
    resume_parser.add_argument("--finish-plan", action="store_true", help="print the safe finish command without running it")
    resume_parser.add_argument("-m", "--message", help="commit message for --finish")
    resume_parser.add_argument("--format", choices=("text", "json"), default="text")
    resume_parser.add_argument("--json", action="store_true", help="alias for --format json")
    resume_parser.add_argument("--no-interactive", action="store_true")
    resume_parser.add_argument("--debug", action="store_true", help="include workspace and canonical attempt details")

    continue_parser = subparsers.add_parser("continue", help="continue the latest interrupted AIT work")
    continue_parser.add_argument("selector", nargs="?", default="latest")
    continue_parser.add_argument("--format", choices=("text", "json"), default="text")
    continue_parser.add_argument("--json", action="store_true", help="alias for --format json")
    continue_parser.add_argument("--no-interactive", action="store_true")
    continue_parser.add_argument("--shell-hook", action="store_true", help=argparse.SUPPRESS)
    continue_parser.add_argument("--shell-reminder", action="store_true", help=argparse.SUPPRESS)

    agent_continue_parser = subparsers.add_parser("agent-continue", help=argparse.SUPPRESS)
    agent_continue_parser.add_argument("--adapter", required=True)
    agent_continue_parser.add_argument("--real-binary", required=True)
    agent_continue_parser.add_argument("agent_args", nargs=argparse.REMAINDER)

    review_parser = subparsers.add_parser("review", help="review an AIT attempt before apply")
    review_parser.add_argument("--format", choices=("text", "json", "markdown"), default="text")
    review_parser.add_argument("--json", action="store_true", help="alias for --format json")
    review_parser.add_argument("--no-interactive", action="store_true")
    review_subparsers = review_parser.add_subparsers(dest="review_command")
    review_attempt = review_subparsers.add_parser("attempt")
    review_attempt.add_argument("selector")
    review_attempt.add_argument("--mode", choices=("light", "adversarial"), default="light")
    review_attempt.add_argument("--review-adapter")
    review_attempt.add_argument("--review-budget", choices=("quick", "standard", "deep"), default="standard")
    review_attempt.add_argument("--format", choices=("text", "json"), default="text")
    review_attempt.add_argument("--json", action="store_true", help="alias for --format json")
    review_attempt.add_argument("--no-interactive", action="store_true")
    review_status = review_subparsers.add_parser("status")
    review_status.add_argument("--status")
    review_status.add_argument("--format", choices=("text", "json"), default="text")
    review_status.add_argument("--json", action="store_true", help="alias for --format json")
    review_status.add_argument("--no-interactive", action="store_true")
    review_worker = review_subparsers.add_parser("worker")
    review_worker.add_argument("--once", action="store_true")
    review_worker.add_argument("--max-jobs", type=int, default=1)
    review_worker.add_argument("--format", choices=("text", "json"), default="text")
    review_worker.add_argument("--json", action="store_true", help="alias for --format json")
    review_worker.add_argument("--no-interactive", action="store_true")
    review_benchmark = review_subparsers.add_parser("benchmark")
    review_benchmark.add_argument("benchmark_command_or_fixture", nargs="?")
    review_benchmark.add_argument("--fixture")
    review_benchmark.add_argument("--input")
    review_benchmark.add_argument("--output")
    review_benchmark.add_argument("--fake-reviewer", default="fake:case")
    review_benchmark.add_argument("--reviewer-adapter", help="real reviewer adapter for explicit --dogfood benchmark runs")
    review_benchmark.add_argument("--dogfood", action="store_true", help="allow local real reviewer invocation for benchmark dogfood")
    review_benchmark.add_argument("--permission-profile", default="read-only", help="permission profile recorded for real reviewer dogfood")
    review_benchmark.add_argument("--model", help="reviewer model label to record when known")
    review_benchmark.add_argument(
        "--timeout-seconds",
        type=int,
        default=DEFAULT_REAL_REVIEWER_BENCHMARK_TIMEOUT_SECONDS,
        help="per-case timeout for real reviewer dogfood",
    )
    review_benchmark.add_argument("--format", choices=("text", "json", "markdown"), default="text")
    review_benchmark.add_argument("--json", action="store_true", help="alias for --format json")
    review_finding = review_subparsers.add_parser("finding")
    review_finding_subparsers = review_finding.add_subparsers(dest="review_finding_command")
    review_finding_list = review_finding_subparsers.add_parser("list")
    review_finding_list.add_argument("--status")
    review_finding_list.add_argument("--severity")
    review_finding_list.add_argument("--format", choices=("text", "json"), default="text")
    review_finding_list.add_argument("--json", action="store_true", help="alias for --format json")
    review_finding_update = review_finding_subparsers.add_parser("update")
    review_finding_update.add_argument("finding_id")
    review_finding_update.add_argument(
        "--status",
        required=True,
        choices=("open", "acknowledged", "fixed", "false_positive", "accepted_risk", "superseded"),
    )
    review_finding_update.add_argument("--reason")
    review_finding_update.add_argument("--format", choices=("text", "json"), default="text")
    review_finding_update.add_argument("--json", action="store_true", help="alias for --format json")
    review_report = review_subparsers.add_parser("report")
    review_report.add_argument("--attempt", default="latest")
    review_report.add_argument("--format", choices=("json", "markdown"), default="json")
    review_report.add_argument("--json", action="store_true", help="alias for --format json")
    review_report.add_argument("--output")
    review_report.add_argument("--no-interactive", action="store_true")

    whereami_parser = subparsers.add_parser("whereami")
    whereami_parser.add_argument("--to")
    whereami_parser.add_argument("--format", choices=("text", "json"), default="text")
    whereami_parser.add_argument("--json", action="store_true", help="alias for --format json")
    whereami_parser.add_argument("--no-interactive", action="store_true")

    next_parser = subparsers.add_parser("next")
    next_parser.add_argument("--to")
    next_parser.add_argument("--explain", action="store_true")
    next_parser.add_argument("--format", choices=("text", "json"), default="text")
    next_parser.add_argument("--json", action="store_true", help="alias for --format json")
    next_parser.add_argument("--no-interactive", action="store_true")

    merge_parser = subparsers.add_parser("merge")
    merge_parser.add_argument("--to")
    merge_parser.add_argument("--mode", choices=("auto", "apply", "ff-only", "merge"), default="auto")
    merge_parser.add_argument("--push", action="store_true")
    merge_parser.add_argument("--set-default-branch", action="store_true")
    merge_parser.add_argument("--dry-run", action="store_true")
    merge_parser.add_argument("--format", choices=("text", "json"), default="text")
    merge_parser.add_argument("--json", action="store_true", help="alias for --format json")
    merge_parser.add_argument("--no-interactive", action="store_true")

    run_parser = subparsers.add_parser("run", help="run an agent command in an isolated AIT attempt")
    run_parser.add_argument("--adapter", choices=tuple(sorted(ADAPTERS)), default="shell")
    run_parser.add_argument("--agent")
    run_parser.add_argument("--intent")
    run_parser.add_argument("--kind")
    run_parser.add_argument("--description")
    run_parser.add_argument("--commit-message")
    run_parser.add_argument("--no-auto-commit", action="store_true")
    run_parser.add_argument("--review", choices=("never", "light", "adversarial", "risk-based"))
    run_parser.add_argument("--review-adapter")
    run_parser.add_argument("--review-budget", choices=("quick", "standard", "deep"), default="standard")
    run_parser.add_argument(
        "--apply",
        choices=("never", "auto", "current", "branch"),
        help="apply policy after a successful run; defaults to repo config or never",
    )
    run_parser.add_argument("--with-context", action="store_true")
    run_parser.add_argument("--format", choices=("json", "text"))
    run_parser.add_argument("--json", action="store_true", help="alias for --format json")
    run_parser.add_argument("--port", type=int, action="append", dest="dev_ports")
    run_parser.add_argument("--check-port", type=int, action="append", dest="dev_check_ports")
    run_parser.add_argument(
        "--stdin",
        choices=("auto", "inherit", "none"),
        default="auto",
        help=(
            "stdin handling for the wrapped command; default 'auto' uses /dev/null for "
            "non-interactive codex exec invocations and otherwise inherits parent stdin. "
            "Use 'none' explicitly for scripted agent CLIs that do not need stdin, or "
            "'inherit' when the wrapped command must read stdin."
        ),
    )
    run_parser.add_argument("run_command", nargs=argparse.REMAINDER)

    dev_parser = subparsers.add_parser("dev")
    dev_subparsers = dev_parser.add_subparsers(dest="dev_command")
    dev_status = dev_subparsers.add_parser("status")
    dev_status.add_argument("--port", type=int, action="append", dest="ports")
    dev_status.add_argument("--format", choices=("text", "json"), default="text")
    dev_preview = dev_subparsers.add_parser("preview")
    dev_preview.add_argument("url")
    dev_preview.add_argument("--file")
    dev_preview.add_argument("--format", choices=("text", "json"), default="text")
    dev_run = dev_subparsers.add_parser("run")
    dev_run.add_argument("--port", type=int, action="append", dest="ports")
    dev_run.add_argument("--format", choices=("text", "json"), default="text")
    dev_run.add_argument("dev_run_command", nargs=argparse.REMAINDER)
    dev_stop = dev_subparsers.add_parser("stop")
    dev_stop.add_argument("--port", type=int)
    dev_stop.add_argument("--force", action="store_true")
    dev_stop.add_argument("--format", choices=("text", "json"), default="text")

    context_parser = subparsers.add_parser("context")
    context_parser.add_argument("intent_id")
    context_parser.add_argument("--format", choices=("text", "json"), default="text")

    memory_parser = subparsers.add_parser("memory")
    memory_parser.add_argument("--limit", type=int, default=8)
    memory_parser.add_argument("--path", dest="path_filter")
    memory_parser.add_argument("--topic")
    memory_parser.add_argument("--promoted-only", action="store_true")
    memory_parser.add_argument("--budget-chars", type=int)
    memory_parser.add_argument("--format", choices=("text", "json"), default="text")
    memory_subparsers = memory_parser.add_subparsers(dest="memory_command")
    memory_facts = memory_subparsers.add_parser("facts")
    memory_facts.add_argument("--status")
    memory_facts.add_argument("--kind")
    memory_facts.add_argument("--topic")
    memory_facts.add_argument("--include-superseded", action="store_true")
    memory_facts.add_argument("--limit", type=int, default=100)
    memory_facts.add_argument("--format", choices=("text", "json"), default="text")
    memory_retrievals = memory_subparsers.add_parser("retrievals")
    memory_retrievals.add_argument("--attempt")
    memory_retrievals.add_argument("--limit", type=int, default=50)
    memory_retrievals.add_argument("--format", choices=("text", "json"), default="text")
    memory_eval = memory_subparsers.add_parser("eval")
    memory_eval.add_argument("--attempt")
    memory_eval.add_argument("--limit", type=int, default=50)
    memory_eval.add_argument("--format", choices=("text", "json"), default="text")
    memory_note = memory_subparsers.add_parser("note")
    memory_note_subparsers = memory_note.add_subparsers(dest="memory_note_command")
    memory_note_add = memory_note_subparsers.add_parser("add")
    memory_note_add.add_argument("body")
    memory_note_add.add_argument("--topic")
    memory_note_add.add_argument("--source", default="manual")
    memory_note_add.add_argument("--format", choices=("text", "json"), default="json")
    memory_note_list = memory_note_subparsers.add_parser("list")
    memory_note_list.add_argument("--topic")
    memory_note_list.add_argument("--limit", type=int, default=100)
    memory_note_list.add_argument("--format", choices=("text", "json"), default="text")
    memory_note_remove = memory_note_subparsers.add_parser("remove")
    memory_note_remove.add_argument("note_id")
    memory_note_remove.add_argument("--format", choices=("text", "json"), default="json")
    memory_search = memory_subparsers.add_parser("search")
    memory_search.add_argument("query")
    memory_search.add_argument("--limit", type=int, default=8)
    memory_search.add_argument("--ranker", choices=("vector", "lexical"), default="vector")
    memory_search.add_argument("--format", choices=("text", "json"), default="text")
    memory_sources = memory_subparsers.add_parser(
        "sources",
        help="list live memory sources without writing .ait/",
    )
    memory_sources.add_argument("--source", default="auto")
    memory_sources.add_argument("--path", action="append", dest="source_paths")
    memory_sources.add_argument("--include-docs", action="store_true")
    memory_sources.add_argument("--global", action="store_true", dest="global_scope")
    memory_sources.add_argument("--format", choices=("text", "json"), default="text")
    memory_recall = memory_subparsers.add_parser("recall")
    memory_recall.add_argument("query", nargs="?")
    memory_recall.add_argument("--auto", action="store_true")
    memory_recall.add_argument("--agent")
    memory_recall.add_argument("--kind")
    memory_recall.add_argument("--description")
    memory_recall.add_argument("--command-text")
    memory_recall.add_argument("--limit", type=int, default=6)
    memory_recall.add_argument("--budget-chars", type=int, default=4000)
    memory_recall.add_argument("--include-unhealthy", action="store_true")
    memory_recall.add_argument("--include-sources", action="store_true")
    memory_recall.add_argument("--record", action="store_true", help="write recall evidence under .ait/")
    memory_recall.add_argument("--path", action="append", dest="source_paths", help="explicit live memory file or directory")
    memory_recall.add_argument("--include-docs", action="store_true")
    memory_recall.add_argument("--global", action="store_true", dest="global_scope", help="allow explicitly provided paths outside the repo")
    memory_recall.add_argument("--format", choices=("text", "json"), default="text")
    memory_lint = memory_subparsers.add_parser("lint")
    memory_lint.add_argument("--fix", action="store_true")
    memory_lint.add_argument("--max-chars", type=int, default=6000)
    memory_lint.add_argument("--format", choices=("text", "json"), default="text")
    memory_backfill = memory_subparsers.add_parser(
        "backfill",
        help="preview agent memory; --import is an explicit .ait/ mutation",
    )
    memory_backfill.add_argument("--source", default="auto", help="agent memory source name")
    memory_backfill.add_argument("--path", action="append", dest="import_paths", help="explicit memory file or directory")
    memory_backfill.add_argument("--topic", default="agent-memory")
    memory_backfill.add_argument("--max-chars", type=int, default=6000)
    memory_backfill.add_argument("--dry-run", action="store_true", help="preview only; write nothing")
    memory_backfill.add_argument("--import", action="store_true", dest="import_matches", help="MUTATION/deprecated: write imported memory under .ait/")
    memory_backfill.add_argument("--global", action="store_true", dest="global_scope", help="allow explicitly provided paths outside the repo")
    memory_backfill.add_argument("--format", choices=("text", "json"), default="text")
    memory_import = memory_subparsers.add_parser("import")
    memory_import.add_argument("--source", default="auto")
    memory_import.add_argument("--path", action="append", dest="import_paths")
    memory_import.add_argument("--topic", default="agent-memory")
    memory_import.add_argument("--max-chars", type=int, default=6000)
    memory_import.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph = memory_subparsers.add_parser("graph")
    memory_graph_subparsers = memory_graph.add_subparsers(dest="memory_graph_command")
    memory_graph_build = memory_graph_subparsers.add_parser("build")
    memory_graph_build.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph_show = memory_graph_subparsers.add_parser("show")
    memory_graph_show.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph_show.add_argument("--budget-chars", type=int)
    memory_graph_query = memory_graph_subparsers.add_parser("query")
    memory_graph_query.add_argument("query")
    memory_graph_query.add_argument("--limit", type=int, default=8)
    memory_graph_query.add_argument("--format", choices=("text", "json"), default="text")
    memory_graph_brief = memory_graph_subparsers.add_parser("brief")
    memory_graph_brief.add_argument("query", nargs="?")
    memory_graph_brief.add_argument("--auto", action="store_true")
    memory_graph_brief.add_argument("--explain", action="store_true")
    memory_graph_brief.add_argument("--agent")
    memory_graph_brief.add_argument("--kind")
    memory_graph_brief.add_argument("--description")
    memory_graph_brief.add_argument("--command-text")
    memory_graph_brief.add_argument("--limit", type=int, default=6)
    memory_graph_brief.add_argument("--budget-chars", type=int, default=5000)
    memory_graph_brief.add_argument("--format", choices=("text", "json"), default="text")
    memory_policy = memory_subparsers.add_parser("policy")
    memory_policy_subparsers = memory_policy.add_subparsers(dest="memory_policy_command")
    memory_policy_init = memory_policy_subparsers.add_parser("init")
    memory_policy_init.add_argument("--force", action="store_true")
    memory_policy_init.add_argument("--format", choices=("text", "json"), default="json")
    memory_policy_show = memory_policy_subparsers.add_parser("show")
    memory_policy_show.add_argument("--format", choices=("text", "json"), default="json")

    bootstrap_parser = subparsers.add_parser("bootstrap")
    bootstrap_parser.add_argument("name", choices=tuple(sorted(ADAPTERS)), nargs="?", default="claude-code")
    bootstrap_parser.add_argument("--format", choices=("text", "json"), default="json")
    bootstrap_parser.add_argument("--shell", action="store_true")
    bootstrap_parser.add_argument("--check", action="store_true")

    doctor_parser = subparsers.add_parser("doctor")
    doctor_parser.add_argument("name", choices=tuple(sorted(ADAPTERS)), nargs="?")
    doctor_parser.add_argument("--format", choices=("text", "json"), default="text")
    doctor_parser.add_argument("--json", action="store_true", help="alias for --format json")
    doctor_parser.add_argument("--no-interactive", action="store_true")
    doctor_parser.add_argument("--fix", action="store_true")

    status_parser = subparsers.add_parser("status")
    status_parser.add_argument("name", choices=tuple(sorted(ADAPTERS)), nargs="?", default="claude-code")
    status_parser.add_argument("--format", choices=("text", "json"), default="text")
    status_parser.add_argument("--json", action="store_true", help="alias for --format json")
    status_parser.add_argument("--no-interactive", action="store_true")
    status_parser.add_argument("--all", action="store_true", dest="all_adapters")
    status_parser.add_argument("--debug", action="store_true", help="include recovery and workspace decision details")

    upgrade_parser = subparsers.add_parser("upgrade")
    upgrade_parser.add_argument("--dry-run", action="store_true")
    upgrade_parser.add_argument("--format", choices=("text", "json"), default="text")

    graph_parser = subparsers.add_parser("graph")
    graph_parser.add_argument("--format", choices=("text", "json"), default="text")
    graph_parser.add_argument("--limit", type=int, default=20)
    graph_parser.add_argument("--html", action="store_true")
    graph_parser.add_argument("--output")
    graph_parser.add_argument("--agent")
    graph_parser.add_argument("--status")
    graph_parser.add_argument("--file", dest="file_path")

    console_parser = subparsers.add_parser("console", help="write or serve the read-only local daily console")
    console_parser.add_argument("--read-only", action="store_true", default=True, help="only read graph data; no mutation actions are available")
    console_parser.add_argument("--format", choices=("text", "json"), default="text")
    console_parser.add_argument("--limit", type=int, default=20)
    console_parser.add_argument("--output")
    console_parser.add_argument("--agent")
    console_parser.add_argument("--status")
    console_parser.add_argument("--file", dest="file_path")
    console_parser.add_argument("--serve-local", action="store_true", help="serve the generated console on a loopback-only HTTP server")
    console_parser.add_argument("--host", default="127.0.0.1", help="loopback host for --serve-local")
    console_parser.add_argument("--port", type=int, default=0, help="port for --serve-local; 0 chooses a free local port")
    console_subparsers = console_parser.add_subparsers(dest="console_command")
    console_action = console_subparsers.add_parser("action")
    console_action_subparsers = console_action.add_subparsers(dest="console_action")
    for name in ("apply", "recover", "discard"):
        action_parser = console_action_subparsers.add_parser(name)
        action_parser.add_argument("--attempt", default="latest")
        action_parser.add_argument("--dry-run", action="store_true", required=True)
        action_parser.add_argument("--actor-label", default="local-user")
        action_parser.add_argument("--format", choices=("text", "json"), default="json")
        action_parser.add_argument("--json", action="store_true", help="alias for --format json")

    repair_parser = subparsers.add_parser("repair")
    repair_parser.add_argument(
        "name",
        choices=tuple(name for name in sorted(ADAPTERS) if name != "shell"),
        nargs="?",
    )
    repair_parser.add_argument("--format", choices=("text", "json"), default="text")

    enable_parser = subparsers.add_parser("enable")
    enable_parser.add_argument(
        "--adapter",
        choices=tuple(name for name in sorted(ADAPTERS) if name != "shell"),
        action="append",
        dest="enable_adapters",
    )
    enable_parser.add_argument("--format", choices=("text", "json"), default="text")
    enable_parser.add_argument("--shell", action="store_true")

    shell_parser = subparsers.add_parser("shell")
    shell_subparsers = shell_parser.add_subparsers(dest="shell_command")
    shell_show = shell_subparsers.add_parser("show")
    shell_show.add_argument("--shell", choices=("zsh", "bash"), default="zsh")
    shell_install = shell_subparsers.add_parser("install")
    shell_install.add_argument("--shell", choices=("zsh", "bash"))
    shell_install.add_argument("--rc-path")
    shell_install.add_argument("--format", choices=("text", "json"), default="text")
    shell_uninstall = shell_subparsers.add_parser("uninstall")
    shell_uninstall.add_argument("--shell", choices=("zsh", "bash"))
    shell_uninstall.add_argument("--rc-path")
    shell_uninstall.add_argument("--format", choices=("text", "json"), default="text")

    adapter_parser = subparsers.add_parser("adapter")
    adapter_subparsers = adapter_parser.add_subparsers(dest="adapter_command")
    adapter_list = adapter_subparsers.add_parser("list")
    adapter_list.add_argument("--format", choices=("table", "json"), default="table")
    adapter_show = adapter_subparsers.add_parser("show")
    adapter_show.add_argument("name", choices=tuple(sorted(ADAPTERS)))
    adapter_show.add_argument("--format", choices=("text", "json"), default="text")
    adapter_doctor = adapter_subparsers.add_parser("doctor")
    adapter_doctor.add_argument("name", choices=tuple(sorted(ADAPTERS)))
    adapter_doctor.add_argument("--format", choices=("text", "json"), default="text")
    adapter_doctor.add_argument("--json", action="store_true", help="alias for --format json")
    adapter_doctor.add_argument("--no-interactive", action="store_true")
    adapter_setup = adapter_subparsers.add_parser("setup")
    adapter_setup.add_argument("name", choices=tuple(sorted(ADAPTERS)))
    adapter_setup.add_argument("--target", default=".claude/settings.json")
    adapter_setup.add_argument("--print", action="store_true", dest="print_only")
    adapter_setup.add_argument("--install-wrapper", action="store_true")
    adapter_setup.add_argument("--install-direnv", action="store_true")

    reconcile_parser = subparsers.add_parser("reconcile")
    reconcile_parser.add_argument("--format", choices=("text", "json"), default="json")
    reconcile_parser.add_argument("--json", action="store_true", help="alias for --format json")
    reconcile_parser.add_argument("--no-interactive", action="store_true")
    reconcile_parser.add_argument("--dry-run", action="store_true")

    daemon_parser = subparsers.add_parser("daemon")
    daemon_subparsers = daemon_parser.add_subparsers(dest="daemon_command")
    daemon_subparsers.add_parser("start")
    daemon_subparsers.add_parser("stop")
    daemon_subparsers.add_parser("prune")
    daemon_subparsers.add_parser("status")
    daemon_subparsers.add_parser("serve")
    return parser
