from __future__ import annotations

import shlex
from dataclasses import dataclass

from ait.bug_report.collector import CollectedEntry
from ait.bug_report.redactor import redact, redact_argv


SCOPE_BANNER = (
    "> Automatically generated by `ait`. Reviewed and submitted by the user.\n"
    "> Reports a bug in **AIT itself** — not the user's code or AI-agent output.\n"
)


@dataclass
class BuildInput:
    entries: list[CollectedEntry]
    ait_version: str
    python_version: str
    os_arch: str
    argv: list[str]
    include_tier2: bool
    include_tier3: bool
    install_nonce: str
    daemon_log_tail: str
    daemon_state: str
    phase: str
    env_vars: dict[str, str]
    extra_transcript: str | None
    repo_id: str | None


@dataclass
class BuiltIssue:
    title: str
    body: str
    primary_fingerprint: str


def _join_argv(argv: list[str]) -> str:
    return " ".join(shlex.quote(a) for a in redact_argv(argv))


def _format_stack(entry: CollectedEntry) -> str:
    lines = [f"{entry.exc_type}: {entry.exc_message}"]
    for frame in entry.frames:
        lines.append(f"  at {frame.function} ({frame.filename})")
    return redact("\n".join(lines))


def build_issue(inp: BuildInput) -> BuiltIssue:
    primary = inp.entries[0]
    short_msg = primary.exc_message.splitlines()[0][:80]
    title = f"[crash] {primary.category} — {short_msg} [{primary.fingerprint}]"

    parts = [SCOPE_BANNER, ""]
    parts.append("## Summary")
    parts.append(f"{primary.category}: {short_msg}")
    parts.append("")
    parts.append("## Environment")
    parts.append(f"- AIT: {inp.ait_version}")
    parts.append(f"- Python: {inp.python_version}")
    parts.append(f"- OS: {inp.os_arch}")
    parts.append("")
    parts.append("## Command")
    parts.append("```")
    parts.append(_join_argv(inp.argv))
    parts.append("```")
    parts.append("")
    parts.append("## Stack Trace")
    parts.append("```")
    parts.append(_format_stack(primary))
    parts.append("```")
    parts.append("")
    if len(inp.entries) > 1:
        parts.append("## Internal Errors (Layer 2)")
        for e in inp.entries:
            parts.append(f"- [{e.category}] {e.exc_message[:60]} (×{e.count})")
        parts.append("")
    if inp.include_tier2:
        parts.append("## Context")
        parts.append(f"- Install ID: {inp.install_nonce}")
        if inp.daemon_state:
            parts.append(f"- Daemon: {inp.daemon_state}")
        if inp.phase:
            parts.append(f"- Phase: {inp.phase}")
        parts.append("")
        if inp.daemon_log_tail:
            parts.append("## Daemon Log Tail (redacted)")
            parts.append("```")
            parts.append(redact(inp.daemon_log_tail))
            parts.append("```")
            parts.append("")
    if inp.include_tier3 and inp.env_vars:
        parts.append("## Environment Variables")
        for k, v in sorted(inp.env_vars.items()):
            parts.append(f"- {k}: {redact(v)}")
        parts.append("")
    if inp.extra_transcript:
        parts.append("## Attached Transcript (high-risk, user-confirmed)")
        parts.append("```")
        parts.append(redact(inp.extra_transcript))
        parts.append("```")
        parts.append("")
    if inp.repo_id:
        parts.append("## Repository ID (high-risk, user-confirmed)")
        parts.append(f"`{inp.repo_id}`")
        parts.append("")
    parts.append("---")
    parts.append(f"Fingerprint: `{primary.fingerprint}`")

    body = "\n".join(parts) + "\n"
    return BuiltIssue(title=title, body=body, primary_fingerprint=primary.fingerprint)
